### ISSUE TITLE
Bot crashes frequently when the DRPG API is down

### ISSUE THREAD

**Issue by Willard21** [Nightorn/Aldebaran#13]
Bot crashes a lot when the DRPG API is down. It shouldn't crash, and should instead tell people that the API isn't working.

**Comment by Ciborn** [comment]
I thought Aldebaran was already doing that though, I need to look at it again

**Comment by Willard21** [comment]
Well, I *thought* it was the drpg API crashing it, since the API is down and the bot is crashing constantly right now. It looks like you're right that it already does it on the commands though.

**Comment by mount2010** [comment]
Is this still an issue?

**Comment by Willard21** [comment]
As far as I know, yeah. Unless Ciborn fixed something in 1.9. I don't know what's causing the crashes, but the bot still restarts a bunch every time the API goes down.

**Comment by Ciborn** [comment]
We will reopen this issue if this problem occurs again; the bot didn't seem to crash anymore when the API was down.

**Comment by Willard21** [comment]
![image](https://user-images.githubusercontent.com/24826881/71451576-eb752500-273e-11ea-84ff-7a4e2db29df6.png)
That was while the API was down yesterday. I think it was just those 2 restarts, then nothing for the next 5 hours before Mackan pulled it back up.

**Comment by Ciborn** [comment]
Then that was probably when someone used &walls with your PR still being opened then
