### ISSUE TITLE
&skills Only Showing Chopping Info

### ISSUE THREAD

**Issue by Feathers8** [Nightorn/Aldebaran#25]
# Describe the bug

Doing `&skills` only shows chopping info.

# Steps To Reproduce

1. Do `&skills`.

# Expected behavior

Also showing info for mining, fishing, and foraging.

# Screenshots

![image](https://user-images.githubusercontent.com/61866504/76095926-fee01000-5f79-11ea-9203-39b179e3d484.png)

# Versions and configuration

v1.10.0

**Comment by Willard21** [comment]
The other sides may have multiple equations since the math is embedded in the item data. I think they're mostly the same within each category, except for essences.

**Comment by Feathers8** [comment]
Shouldn't this be closed btw?

**Comment by Willard21** [comment]
Smh :b:ad Ciborn doesn't know how to auto-close issues with PRs.
